### ISSUE TITLE
With `name="title"`, windowlist should update as soon as title changes

### ISSUE THREAD

**Issue by tuurep** [tuurep/windowlist#6]
Follow-up to https://github.com/tuurep/windowlist/pull/4

> When a window's title changes, it doesn't update in polybar until after one of the following events:
> * Window focus changes
> * New window added / window removed
> * Window geometry changes

It's very common that for example the active window's title changes, but gets stuck as the old one forcing you to do something from the above list to refresh it.

This is a similar issue to what I was working on much earlier with sort-by-position in https://github.com/tuurep/windowlist/commit/49e54bf29327d7ab577c23c46df625b306fa2c02

Investigation needed: how can we listen to the event that `WM_NAME` changes?

**Comment by lazylace37** [comment]
Hi, I've found a quick and easy way to listen to the change for the active window's title only.

Is it OK if I prepare a draft PR or did you want to listen to every window's events?

**Comment by tuurep** [comment]
> did you want to listen to every window's events?

I actually did think of this as well: yeah a complete solution should listen to all windows, take as an example a chat application where the number of unread messages is in the title, and you receive a new message.

But yeah of course, I'm very interested in what you found. With the above, do you still wanna draft a PR?

In either case, can you tell me more? :)

Thank you
